[project]
name = "maia2-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.2",
    "numpy>=2.3.5",
    "onnxruntime>=1.23.2",
    "torch>=2.9.1",
]
